version: "3.0"

services:

### MariaDB Container #######################################

    mariadb:
      build:
        context: ./mariadb
        args:
          MARIADB_IMAGE: ${MARIADB_IMAGE}
      volumes:
        - mariadb:/var/lib/mysql
        - /srv/dev-disk-by-label-SeagateA/appdata/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "${MARIADB_PORT}:3306"
      environment:
        - MYSQL_DATABASE=${MARIADB_DATABASE}
        - MYSQL_USER=${MARIADB_USER}
        - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      restart: unless-stopped

### phpMyAdmin Container ####################################

    phpmyadmin:
      build:
        context: ./phpmyadmin
        args:
          PMA_IMAGE: ${PMA_IMAGE}
      environment:
        - PMA_ARBITRARY=1
      ports:
        - "${PMA_PORT}:80"
      depends_on:
        - "mariadb"
      restart: unless-stopped

### Shinobi Container #######################################

    shinobi:
      image: ${SHINOBI_IMAGE}
      depends_on:
        - "mariadb"
      ports:
        - "8081:8080"
      environment:
        - DATABASE_HOST=mariadb
        - DATABASE_USER=${SHINOBI_DB_USER}
        - DATABASE_PASSWORD=${SHINOBI_DB_PASSWORD}
        - DATABASE_PORT=${SHINOBI_DB_PORT}
      volumes:
        - /srv/dev-disk-by-label-SeagateA/appdata/shinobi/config:/config
        - /srv/dev-disk-by-label-WDGreen/webcam/videos:/opt/shinobi/videos
        - /srv/dev-disk-by-label-SeagateA/appdata/shinobi/datadir:/var/lib/mysql
        - /dev/shm/shinobiDockerTemp:/dev/shm/streams
      restart: unless-stopped


### Volumes Setup #############################################

volumes:
  mariadb:
